
context: |
    Verfasse Website für die Zahnarztpraxis. Schreibe in Deutsch. Schreibe kurz, prägnant und SEO optimiert.
    Die Zahnarztpraxis Dr. Wischmeyer ist in Dormagen und exisitiert seit 1992.

context_file: ./target/customer-information.txt

templates_dir: ./templates
output_dir: ./target
